language: go

sudo: false

go:
#- 1.3
#- 1.4
#- 1.5
#- 1.5.1
#- 1.5.2
#- 1.5.3
#- 1.6
- 1.7
- 1.8
- tip

before_install:
- go get -u github.com/axw/gocov/gocov
- go get -u github.com/mattn/goveralls
- go get golang.org/x/tools/cmd/cover

matrix:
  allow_failures:
#  - go: 1.5.3
  - go: tip

script:
- make build
- make test
- make examples
- make cover
- goveralls -service=travis-ci -v -covermode=count -coverprofile=profile.out
